disabled_rules:
  - trailing_whitespace
  - force_unwrapping
  - force_try
  - function_body_length
  - file_length
  - type_body_length
  - cyclomatic_complexity

opt_in_rules:
  - empty_count
  - explicit_init
  - first_where

included:
  - Sources
  - Tests
