title: VideoToolbox Remote
description: "Remote VideoToolbox for FFmpeg: use a Mac or Apple Silicon system over LAN as an IP-based H.264/HEVC encode/decode/transcoding accelerator"
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
baseurl: "/videotoolbox_remote"
url: "https://davelindo.github.io"
defaults:
  - scope:
      path: ""
    values:
      layout: default
